/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppDisplayTable {
    'pageSize': number;
    'results': number;
    'url': string;
  }
  interface AppFetchData {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppDisplayTableElement extends Components.AppDisplayTable, HTMLStencilElement {}
  var HTMLAppDisplayTableElement: {
    prototype: HTMLAppDisplayTableElement;
    new (): HTMLAppDisplayTableElement;
  };

  interface HTMLAppFetchDataElement extends Components.AppFetchData, HTMLStencilElement {}
  var HTMLAppFetchDataElement: {
    prototype: HTMLAppFetchDataElement;
    new (): HTMLAppFetchDataElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-display-table': HTMLAppDisplayTableElement;
    'app-fetch-data': HTMLAppFetchDataElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppDisplayTable extends JSXBase.HTMLAttributes<HTMLAppDisplayTableElement> {
    'onGetData'?: (event: CustomEvent<any>) => void;
    'pageSize'?: number;
    'results'?: number;
    'url'?: string;
  }
  interface AppFetchData extends JSXBase.HTMLAttributes<HTMLAppFetchDataElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}

  interface IntrinsicElements {
    'app-display-table': AppDisplayTable;
    'app-fetch-data': AppFetchData;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


